apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-template
  namespace: sdyxmall
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-template
        version: v1.0
    spec:
      containers:
        - name: go-template
          image: reg.miz.so/jike/go-template:#tag
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 70m
              memory: 128Mi
            requests:
              cpu: 70m
              memory: 64Mi
          volumeMounts:
            - name: go-template-vol
              mountPath: /data/logs
          command: ["/bin/sh","-c"]
          args: ["./go-template -conf config"]
      volumes:
        - name: go-template-vol
          hostPath:
            path: /data/logs
