apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-template
  namespace: sdyxmall
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-template
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20
